runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: ssl
  version: latest
- name: jinja2
  version: latest

handlers:
- url: /static
  static_dir: static
- url: /.*
  script: main.app
  secure: always
- url: /cron/.*
  script: main.app
  login: admin